name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'ml-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ml-frontend

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ml-frontend/package-lock.json

      - name: Instalar dependencias
        run: npm install

      - name: Build React
        run: npm run build

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy con rsync
        run: |
          rsync -avz --delete \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          build/ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/frontend
