name: Deploy Backend

on:
  # El backend espera a que el frontend termine
  workflow_run:
    workflows: ["Deploy Frontend"] # Asegúrate de que el archivo del frontend tenga exactamente este "name"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Solo ejecuta si el frontend fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to VPS y Reiniciar Servicios
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /var/www/html
            
            # 1. Traer los últimos cambios
            git pull origin main

            # 2. Generar el archivo .env dinámicamente para producción
            # Se usa el bloque cat << EOF para escribir todas las variables de una vez
            cat << EOF > ml-backend/.env
            PROJECT_NAME="PrediccionML"
            DATABASE_URL="${{ secrets.DATABASE_URL }}"
            API_V1_STR="/api/v1"
            SECRET_KEY="${{ secrets.SECRET_KEY_DATABASE }}"
            ALGORITHM="HS256"
            ACCESS_TOKEN_EXPIRE_MINUTES="60"
            ENVIRONMENT="${{ vars.ENVIRONMENT }}"
            FINNHUB_API_KEY="${{ secrets.FINNHUB_API_KEY }}"
            CORS_ORIGINS='${{ vars.CORS_ORIGINS }}'
            EOF
            
            echo "Archivo .env generado exitosamente con ENVIRONMENT=${{ vars.ENVIRONMENT }}"
            
            # 3. Actualizar dependencias de Python
            source venv/bin/activate
            cd ml-backend/
            pip install -r requirements-prod.txt
            
            # 4. Reiniciar el servicio de Ubuntu (Ahora el usuario github tiene permiso)
            sudo systemctl restart tesisml
            
            echo "Backend actualizado y servicio reiniciado exitosamente."